spring.application.name=spring-ai-documentation

#enable multiple client for the application
spring.ai.chat.client.enabled=false

spring.ai.openai.api-key=${OPENAI_API_KEY}

#ollama configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen2.5:3b
# comment for LLM's
#spring.ai.ollama.chat.options.temperature=0
spring.http.clients.connect-timeout=60s
spring.http.clients.read-timeout=300s