spring.application.name=spring-ai-documentation

#enable multiple client for the application
spring.ai.chat.client.enabled=false

spring.ai.openai.api-key=${OPENAI_API_KEY}

#ollama configuration
spring.ai.ollama.base-url=http://localhost:11434
# tinyllama does not work for spring boot . The bare minimum is phi3 mini
#spring.ai.ollama.chat.model=tinyllama
spring.ai.ollama.chat.model=qwen2.5:3b
spring.ai.ollama.chat.options.temperature=0.1
spring.ai.ollama.chat.options.num-predict=150
# comment for LLM's
#spring.ai.ollama.chat.options.temperature=0
spring.http.clients.connect-timeout=60s
spring.http.clients.read-timeout=300s